Issue  #51: Allow users to create audit templates
Fruity-Loops/ALTA pull request #184
Opened 2020-12-13 03:19 UTC by KhaledBadran

This PR introduces the functionality of creating audit templates which is user story #51.

For details on implementation:
- In the server, a model, view and serilizer is introduced for audit templates
- In the client, two components are introduced:
    A) AuditTemplateComponenet: to display the created templates. This component is accessed from the _Template_ tab on the navigation menu
    B) CreateAuditTemplateComponenet: A form to create an audit template. Can be accessed from the _Create Template_ tab on the navigation menu

2020-12-24 18:13 UTC, Amanda-Kolopa commented on client/src/app/components/audit-template/audit-template.component.ts
> +  // ];
Do we need this?
If not, please remove it.

2020-12-24 18:13 UTC, Amanda-Kolopa commented on client/src/app/components/create-audit-template/create-audit-template.component.html
> +              <input matInput id="title" type="text" formControlName="title" placeholder="title"/>
Can we change the placeholder value to Title instead of title?

2020-12-24 18:14 UTC, Amanda-Kolopa commented on client/src/app/components/create-audit-template/create-audit-template.component.html
> +                Comma Separated Integers Only (e.g., 1,4,11)
In the dummy data file, Bins also contain letters.

2020-12-24 18:15 UTC, Amanda-Kolopa commented on client/src/app/components/create-audit-template/create-audit-template.component.ts
> +      serial_number: [''],
The templates should also consider auditing multiple parts and serial numbers

2020-12-24 18:15 UTC, Amanda-Kolopa commented on client/src/app/models/audit-template.ts
> +    serial_number: string;
Same as the previous comment: please change these to accept Arrays as well

2020-12-24 18:16 UTC, Amanda-Kolopa commented on server/audit_template/models.py
> +    serial_number = models.CharField(max_length=256, blank=True)
Same as the previous comment: please change these to JSONField

2020-12-24 18:17 UTC, Amanda-Kolopa requested changes
So far, everything is looking good!

I noticed some things that need to be modified:

- All created templates are visible between the organizations. This needs to be changed to associate templates with their organization.

- I updated issue #51 to contain the most recent mockups. Please update the frontend to represent these designs.

- We will also need some backend tests for this component. Please include these when you have a chance.

- The templates should also consider multiple part_numbers and serial_numbers. I tried to leave comments on the lines of code to make the changes a bit quicker :slightly_smiling_face:

- Bin values can contain letters and numbers

Thank you for the great work!

2021-01-08 22:53 UTC, domludera requested changes
While creating the template, the "Selected Fields" tags should match the input zones on the left, ie. makes sure to filter the underscores on the tags too

2021-01-08 22:53 UTC, domludera commented on client/src/app/components/audit-template/create-audit-template/create-audit-template.component.html
> +<!--      <br>-->
If this is dead code, please remove it

2021-01-09 00:13 UTC, NicholasNagy commented
I fixed all the changes @domludera and @Amanda-Kolopa , the PR should be good to go!

2021-01-09 00:23 UTC, domludera approved these changes

2021-01-09 00:37 UTC, Amanda-Kolopa approved these changes

2021-01-09 00:37 UTC, merged