Organization management
Fruity-Loops/ALTA pull request #204
Opened 2021-01-13 19:10 UTC by NicholasNagy

This PR addresses 3 user stories #71 #189  #191 (1.3A, 1.3B and 1.3C).

Much of the creation functionality was reused, however there are many changes in the front end in order to realize the new design for this feature in our system.

The changes include, putting the creation and editing of organizations on their own separate page, and updating the table to reflect the design in the mockups. This included adding a field to the organizations model in order to allow the storage of the date the organization was created.

2021-01-14 19:39 UTC, Amanda-Kolopa commented on client/src/app/components/manage-organizations/create-organization/create-organization.component.ts
> +  activeStates = ['Active', 'Disabled'];
This isn't being used since creation sets account status to _active_ by default
Can we remove it?

2021-01-14 19:39 UTC, Amanda-Kolopa commented on client/src/app/components/manage-organizations/create-organization/create-organization.component.ts
> +  isActive = '';
This isn't being used either
Can we remove it?

2021-01-14 19:39 UTC, Amanda-Kolopa requested changes
Awesome work! :smile: 

Some required changes:

- Can you add a bit of spacing between the mat-card-footer and the buttons, please? (same for Organization Profile page)
![image](https://user-images.githubusercontent.com/19229712/104530634-60c9c700-55da-11eb-996f-ca73bc2ad03b.png)

- We should change the single dot in the _Settings_ column of the Organization table to 3 vertical dots 

- Attempting to create an organization without a location returns a 400 (Bad Request) error

- The creation page does not display an error message when trying to create an organization using a name that already exists in the database

- When setting the organization's account status to _disabled_, a popup should appear requesting the user to enter the organization's name to confirm the action

- The _Edit Organization_ page should not have an input field for Location. It should display the most recent .csv file and a button to update the organization's locations

2021-01-18 01:59 UTC, Amanda-Kolopa requested changes
Thank you for the quick changes!

Small note:

- the _Disable Organization_ popup should have an input field that accepts the organization's name as confirmation 

Aside from this, all else is good :smile:

2021-01-18 04:31 UTC, NicholasNagy commented
Hey @Amanda-Kolopa , 

I finished making all the requested changes, please have one last look!

Thanks

2021-01-18 15:18 UTC, Amanda-Kolopa approved these changes
Thank you for the final modification!
This PR is good to merge :slightly_smiling_face:

2021-01-18 15:19 UTC, merged