Reset password
Fruity-Loops/ALTA pull request #284
Opened 2021-04-03 14:45 UTC by RobertBeaudenon

- Click on the forgot password on the login page
- Enter your email
- Receive an email with the link 
- Past the link in your browser and change your password
- Make sure to have a valid sender email address in your env file else it wont send an email

2021-04-05 17:42 UTC, NicholasNagy requested changes
Aside from the comments mentioned, the functionality seems to work as intended, but the UI/feedback needs to be improved.

If the e-mail doesn't exist, there is no feedback to tell the user that, and nothing is mentioned to indicate that the e-mail was sent successfully. Additionally, the look of the UI doesn't match the mockups.

2021-04-06 05:41 UTC, NicholasNagy commented on client/src/app/components/employees/employee-view/edit-employee/edit-employee.component.ts
> +      console.log(this.id);
After discussing with Robert offline, we decided it would be best to remove these debugging statements

2021-04-06 05:41 UTC, NicholasNagy commented on client/src/app/guards/auth.guard.ts
> +      console.log('here');
After discussing with Robert offline, we decided it would be best to remove these debugging statements

2021-04-06 06:15 UTC, NicholasNagy commented on client/src/app/components/login/login.component.ts
> +        this.populateUserInfo(data, true);
Okay, I added it into the doc

2021-04-06 06:19 UTC, NicholasNagy reviewed
Alright, so I  made the required changes that I thought needed for this feature, the only things I am unsure about now are whether we should have a timeout on a successful email sent (since we might want them to have all the necessary time to check the next instructions), and whether the colors of the placement/success look nice. 

I sent the images already to @Amanda-Kolopa , but I will include them here for anyone who wants to give feedback. The features are different ideas (so the box above or below the text, the outline or not).

![image](https://user-images.githubusercontent.com/40705372/113667140-56b9e080-967e-11eb-972b-e7d9cffa1080.png)
![image](https://user-images.githubusercontent.com/40705372/113667155-5de0ee80-967e-11eb-9210-91bac90b84c4.png)
![image](https://user-images.githubusercontent.com/40705372/113667170-63d6cf80-967e-11eb-97c5-d39cf69aad0e.png)
![image](https://user-images.githubusercontent.com/40705372/113667199-6d603780-967e-11eb-9894-a68a94d24332.png)

2021-04-08 00:30 UTC, Amanda-Kolopa requested changes
Overall, great work guys! :smile: 

Small note: 
- can we change the white popup box to offer a _Close_ button once a successful email has been submitted instead of the timeout? The green success rectangle should also remain present until the user closes the popup box.

2021-04-08 16:38 UTC, Amanda-Kolopa commented
Thank you for the quick changes!

Before merging, I noticed something which needs to be modified:

A stock-keeper is able to use their email address and reset their password, which should be restricted since their accounts rely on pin authorization.

2021-04-08 16:40 UTC, NicholasNagy commented
Awesome, thanks for pointing that out Amanda, I just fixed it. Please try all 3 cases (as SK, SA and IM) to see if everything works as expected once more when you have the chance :)

2021-04-08 16:59 UTC, Amanda-Kolopa approved these changes
Everything looks good now!
Thank you for the awesome work  :smile:

2021-04-08 17:02 UTC, NicholasNagy approved these changes
I have no more changes left to do, so it should be good to merge now :).

2021-04-08 17:02 UTC, merged